services:
  app:
    image: devops1109/jwt-crud-api
    container_name: jwt-app
    environment:
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/jwtcrud
      - JWT_SECRET=b9999982a26873a461296a4866b7af1b631f5a1c30825649d447fd5e047ee45cc9bf01eba804af55307c6bd60670555b581e95848edb1eef63f67cedd8a6fb63
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo-db
    networks:
      - app-network
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
